### PR TITLE
Pocketrocket-class multipurpose ship

### PR DESCRIPTION
**Pull request by BBBBAface**
## About The Pull Request

Adds the smallest ship I could make while still being usable as a ship as-is. The only options for smaller ships are very barebones or only have 1/2 rooms, which I didn't like. 

## Why It's Good For The Game

We need more small ships, as they seem to be the most popular size of ship to purchase, be it because of price or because of customizability.

## Changelog
:cl:
add: pocketrocket
/:cl:

### CODE REVIEW

**Comment by HolyTigerGod** [comment]
It doesnt have mobile port and a json file

**Comment by BBBBAface** [comment]
> It doesnt have mobile port and a json file

i forgot the ghot dang mobile port smh

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
My guy have you even tested this? You can't just slap a default docking port on ships, that will never work.

**Review by GuiltyNeko — APPROVED** [review]
I hate docking port code

**Comment by u-have-small-pp** [comment]
bro it dont even have autolathe bord how you suposed to get started

**Comment by BBBBAface** [comment]
> bro it dont even have autolathe bord how you suposed to get started

it does, you just dont know how to see that it does apparently

**Pull request merged**
