### PR TITLE
Overhaul of Entire Codebase

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About The Pull Request

It changes almost every single file, and also works just fine on testing several times. 
CREDIT GOES TO THE OWNERS OF ALL THE SAID SPRITES I USED. I really have used way too many to list people by name, so you will have to suffice with this.

## Why It's Good For The Game

It's good for the server due to the massive updates.

## Changelog
:cl:
add: Added more mobs, and more clothes.
del: I can't remember (Old tiles)
balance: Rebalanced NT and Syndie mobs.
fix: Fixed several things.
soundadd: Added NT death sound, and more jukebox music.
code: ALL THE CODE.
/:cl:
image
https://cdn.discordapp.com/attachments/1074290242879754311/1195880352670044170/f5a9ac540abe0db0bc47f9292bc4ee69.mp4?ex=65b5995e&is=65a3245e&hm=0ae6583ccbed1258284b3ff27f5143f084836d1583cd8ccf4d89898b5fa0602a&
https://cdn.discordapp.com/attachments/1074290242879754311/1195855593672544286/825ba67cc04a414a519d56a1da76da23.mp4?ex=65b5824f&is=65a30d4f&hm=1080838b124392d07c21929743da0d91b29834c76f60185065e2337713bd9254&
image
image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by Addust** [comment]
by ratvar

ALY LOOK AT THIS SHIT

**Comment by BBBBAface** [comment]
I like how you used the tartarus for a screenshot when it isnt actually spawnable ingame and hasnt been for quite a while

**Comment by ChromeFoxxity** [comment]
> I like how you used the tartarus for a screenshot when it isnt actually spawnable ingame and hasnt been for quite a while

I just used images that I posted to coworkers. Was too lazy to get anything big.

**Comment by Imaginos16** [comment]
Hey there! I couldn't help but notice that several of my sprites (the entirety of SolGov) has gone completely uncredited, along with sprites made by several other spriters, such as @Ebin-Halcyon (who made Inteq) and @axietheaxolotl (who has done the HoP sprites that were poorly recolored). Please credit them in the PR body.

**Comment by ChromeFoxxity** [comment]
I was unaware, nor was I even able to know who made what. I would have made
my own junk, but unfortunately I don't think I'm that advanced at making
uniforms that even look good, nor look right. I would have credited if it
weren't that I couldn't have even found the people who made the sprites
even if I tried.

**Comment by BBBBAface** [comment]
you should start a new pr at this point instead of adding to it forever

**Comment by thgvr** [comment]
You're still gonna need to credit all of the sprites you're taking.

**Comment by thgvr** [comment]
Just a heads up - these sprites are *still* licensed under CC BY-NC-SA 3.0 (https://creativecommons.org/licenses/by-nc-sa/3.0/), which clearly states that appropriate credit must be given for the assets you are taking. I recommend doing this if you plan to have this PR merged.

**Comment by Veiyna** [comment]
Really? Did you just merge a PR that completely breaks a few ships and doesn't have credits for the sprite authors?

**Comment by KingDoogan** [comment]
> Really? Did you just merge a PR that completely breaks a few ships and doesn't have credits for the sprite authors?

I pre-tested the additional ships, passed all checks > pre-merge on my local with no issues + build worked fine.

**Comment by retlaw34** [comment]
I'll be real with you, there is just, so much blatant plagiarism here that it's hard to belive this was accidental. In fact, so much shit is stolen that the people who came up to you to report said plagiarism didn't even notice all of their shit that was stolen, just the stuff they recognized

i went through this to grab a single screenshot of stuff that was stolen, but I REALLY should not have done that as I have found, so much of my shit uncredited, and even non-spriters shit like coders and mappers who I didn't even want to involve in this shit's who was stolen. It's kind of insane you shamelessly steal all of this then have the audacity to have spriters ASK you for credit rather than just fucking, putting in the bare minimum of work to look up the PR things were added in, linking said PR, and credit, instead of hiding behind the excuse that "theres so many changes that you can't credit everything!" because you absolutely can! See https://github.com/shiptest-ss13/Shiptest/pull/484 for chirst sake.

you can't even make the excuse that you 'forgot to credit because of all the changes.' It quite literally looks like you literally copy and pasted /TG/station code and shiptest code.  (pretty obvious as you copied an blatant bug from one of my PRs line for line, lmao)

This is how you credit things: You make a single, small pull request, credit the people you use the sprites, code, and maps of, for a single feature for example:

The code for your tiles is stolen from https://github.com/tgstation/tgstation/pull/58932 . Make a new pr with JUST the tile changes and port it. Link the original. Done.

That's called 'atomiziation' and also 'crediting' , and you somehow failed all that.

I understand if this comes off as aggressive and thats because it IS, Not only am I pissed at my shit being plagiarized, but also many other shiptest contributor's shit being plagiarized; not just that, the hard work of /TG/station contributors as well. How the hell does anyone get away with this without being questioned is beyond me

Thats my rant, feel free to disregard it like the other contributor's comments you clearly ignored.

**Comment by KingDoogan** [comment]
@retlaw34 

Since attribution / crediting contributions seems to be an issue here.

1. Are you able to provide a full detailed list? or get help doing so, by mentioning others or authors so I can personally add these credits. ( Sprites / Images Used )

2. As for Code. Under GNU GPL v3 and or GNU AGPL v3. contributors are not explicitly required to mention that their code comes from another source, only have to keep the GPL - AGPL license's listed with any source material. However, if someone has uploaded their code and there are lines in it like this: ##Code by billy bob ( You're not allowed to remove this line )

^ This includes all text based input ( including maps ). not images/sprites (those are purely CC if they're not royalty free images or OTHER) that is what I am here to sort out.

BUT If anyone likes to be credited for recent code or maps. I can add those as well for everyone's peace of mind even though it's not required.

Feel free to reach me via discord: Alixa. (with the . ) If there are any further conflicts or concerns.

**Pull request merged**
