### PR TITLE
Create xetis.dmm

### PR DESCRIPTION
**Pull request by hako01**
## About The Pull Request

I made a xenomorph themed Metis variant, I have no name for it so I named the file xetis if a real name pops up, I'll rename it.

## Why It's Good For The Game

I wouldn't call it good for the game, but I think it'll be fun?

## Changelog
:cl:
created the ship xetis.dmm.
made the json file it should work now.
:cl:
ship image

### CODE REVIEW

**Comment by hako01** [comment]
Side note, I think I can do the coding side if I'm pointed at where it goes

**Comment by hako01** [comment]
map area is broken I'll need to fix it, give me a bit to get back to it and fix the containment area

**Comment by BBBBAface** [comment]
very epic

**Comment by hako01** [comment]
final ship image after some minor deletions of weapons and posibrain

**Comment by hako01** [comment]
Okay I see the issue now after reading the error

**Comment by hako01** [comment]
it should be done and ready to be pushed up.

**Pull request closed without merging**
